# Generated by Django 2.2.1 on 2020-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_auto_20200220_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
